### ISSUE TITLE
Models.query().withAll().where(model => { console.log(model) }) always returns free of nested data instance. 

### ISSUE THREAD

**Issue by bonduell** [revolver-app/vuex-orm#755] opened 2021-09-16 07:57 UTC
#### Describe the bug

Models.query().withAll().where(model => { console.log(model) }) always returns free of nested data instance. 

I would like use where(model => model.nestedData.id === value).orderBy("model.nestedData.title", 'asc | desc')
but it's impossible if query.whereAll() doesn't affect model

in case where - I can use whereHas('nestedData' => ...), but what should i do if i'd like to order Models by nestedData?

**Comment by cuebit** [comment] 2021-09-16 08:23
Duplicate of #677

Conditions such as `where` and `orderBy` are applied before relations are loaded by `with` or `withAll`.

While you can order nested relation sets by explicit relation queries i.e. `with('user', query => { query.orderBy('name') })`, you will want to apply your own sort comparator to order by nested items on the resulting data. 

See my comment in the linked issue for more details.

**Comment by bonduell** [comment] 2021-09-16 08:47
It would be great to create query with nested data depended on where whereAll() method inserted.

4ex: 
Model.query().whereAll().where(model=> { returns model with nestedData } )
 and in case of
Model.query().where(model->{ return without nestedData}).withAll()

**Comment by cuebit** [comment] 2021-09-16 09:01
That can currently only be done by explicit `with` queries and passing in closures to narrow the results like the user example above. 

A `withAll` doesn't make sense in this case where you want to be selective on the nested relations you want to load. 

Have you looked into the `whereHas` modifier?

**Comment by cuebit** [comment] 2021-10-15 08:27
Closing due to inactivity. Feel free to open a new issue 👍

**Closed as completed by cuebit** 2021-10-15 08:27 UTC
